version: '3.1'

services:

  db:
    image: mysql:latest
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: warehouse-management

  wt-api:
    depends_on:
      - db
    build: ./warehouse-transfer-api
    ports:
     - 8081:8081
    environment:
      WAIT_HOSTS: db:3306

  wt-client:
    depends_on:
      - wt-api
    build: ./warehouse-transfer-client
    ports:
     - 8080:8080
    environment:
      WAIT_HOSTS: db:3306