version: '3.1'

services:

  db:
    build: ./db-dump
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: warehouse-management
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    networks:
     - wt-network

  wt-api:
    depends_on:
      - db
    build: ./warehouse-transfer-api
    ports:
     - 8081:8081
    links:
     - db:db
    networks:
     - wt-network

  wt-client:
    depends_on:
      - wt-api
    build: ./warehouse-transfer-client
    ports:
     - 8080:8080
    links:
     - db:db
    networks:
     - wt-network

networks:
 wt-network:
  driver: bridge